vla_bridge_node:
  ros__parameters:
    model_id: /home/jetson/Shu/smol_rugv/models/smolvla_ugv_moveaway_finetune/checkpoints/last/pretrained_model
    inference_rate: 10.0
    default_instruction: "move away from the column"
